version: '3'

services:
  app:
    build: abbakumov/cosmetos:latest
    ports:
      - 3000:3000
    volumes:
      - ${COSMETOS_UPLOADS_PATH}:/usr/src/app/static/uploads
    environment:
      - COSMETOS_SECRET
      - PG_HOST
      - PG_LOGIN
      - PG_PASSWORD
  nginx:
    image: nginx:1.17.6
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf