export const PAGE_ADM_PROD_UN_OPEN_PRODUCT = 'PAGE_ADM_PROD_UN_OPEN_PRODUCT';
export const PAGE_ADM_PROD_UN_SAVE_PRODUCT = 'PAGE_ADM_PROD_UN_SAVE_PRODUCT';
export const PAGE_ADM_PROD_UN_SEARCH_PRODUCT = 'PAGE_ADM_PROD_UN_SEARCH_PRODUCT';
